apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      apps: mydeployment
  template:
    metadata:
      name: testpod
      labels:
        apps: mydeployment
        devservice: dev
    spec:
      containers:
        - name: web
          image: httpd
          ports:
            - containerPort: 80
          env:
            - name: name
              value: "aditya"
            - name : mapvalue
          envFrom:
            - configMapRef:
                name: myconfigmap
