apiVersion: v1
kind: ConfigMap
metadata:
  name: newconfig
data:
  config.json: |-
    {
      "friendsname": "myfriend",
      "middlename": "pratap",
      "surname": "bais",
      "newname": "aditya"
      "johny": "bairstow"
    }
  name.json: |-
    {
      "sachin": "cricket"
    }

