apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
    - image: ubuntu
      name: app1
      env:
        - name: name
          value: aditya
      command: ["/bin/bash","-c","while true; do echo aditya;sleep 5;done;"]
