apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      apps: mydeployment
  template:
    metadata:
      name: testpod
      labels:
        apps: mydeployment
        devservice: dev
    spec:
      containers:
        - name: testpod
          image: ubuntu
          command: ["/bin/bash","-c","while true; do echo aditya;sleep 5;done;"]
          volumeMounts:
            - name: config
              mountPath: "/temp"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: newconfig

